# Generated by Django 6.0.3 on 2026-04-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
        ('reader', '0003_unlockedpage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user_id', 'book', 'page_number')},
        ),
    ]
