# Generated by Django 6.0.3 on 2026-04-09 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
        ('reader', '0004_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnlockedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('chapter_number', models.PositiveIntegerField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_chapters', to='books.book')),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user_id', 'book'], name='reader_unlo_user_id_2dc349_idx'), models.Index(fields=['user_id', 'book', 'chapter_number'], name='reader_unlo_user_id_a56258_idx')],
                'unique_together': {('user_id', 'book', 'chapter_number')},
            },
        ),
    ]
