# Generated by Django 6.0.3 on 2026-04-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paystackpayment',
            name='country_code',
            field=models.CharField(default='KE', help_text='Country code', max_length=2),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='currency',
            field=models.CharField(default='KES', help_text='Original currency used', max_length=3),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='local_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount in original currency', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in KES (base currency)', max_digits=10),
        ),
    ]
