# Generated by Django 6.0.3 on 2026-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookchapter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Price to unlock this chapter', max_digits=10),
        ),
    ]
